# Generated by Django 5.2.1 on 2025-05-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
    ]
