# Generated by Django 5.2.1 on 2025-05-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repeat_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
