# Generated by Django 5.2.1 on 2025-05-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chatroom_message_typingstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chatroom',
        ),
        migrations.RemoveField(
            model_name='typingstatus',
            name='chatroom',
        ),
        migrations.RemoveField(
            model_name='message',
            name='mentioned_users',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='typingstatus',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='TypingStatus',
        ),
    ]
