# Generated by Django 5.2.1 on 2025-05-29 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chatroom_message_typingstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='mentions', to=settings.AUTH_USER_MODEL),
        ),
    ]
