# Generated by Django 5.2.1 on 2025-05-29 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_message_content_alter_message_mentioned_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentions', to=settings.AUTH_USER_MODEL),
        ),
    ]
